### ISSUE TITLE
Compatibility with eslint 4

### ISSUE THREAD

**Issue by ManasJayanth** [jquense/eslint-config-jason#1]
When working on react-dom-lite, yarn complains of eslint-config-jason to be incompatible with eslint 4. 

```bash
eslint-config-jason@4.0.0" has incorrect peer dependency "eslint@^3.3.1".
```

Can you please support eslint 4 to prevent those warnings? Thank you :)

**Comment by ManasJayanth** [comment]
On skimming through the rules, I couldn't find anything eslint 3 specific? Can we simply bump the peer dependency entry?

**Comment by jquense** [comment]
> Can we simply bump the peer dependency entry?

yup
